### ISSUE TITLE
Create Anki cards

### ISSUE THREAD

**Issue by juanj** [juanj/KantanManga#14] opened 2020-09-06 18:48 UTC
- [x] Add button to definitions
- [X] Create Add Anki Card view
- [X] Save Anki cards locally
- [x] Show local Anki cards
- [x] Sync Anki card using [AnkiConnect](https://github.com/FooSoft/anki-connect)

**Comment by JoshuaRamey** [comment] 2021-09-18 13:51
@juanj How is the progress going with this? Do you think it will be possible to add cards to anki from the app? I'm really looking forward to this update. Currently I take screenshots and use those to make cards but it's kind of tedious to do in bulk.

**Comment by juanj** [comment] 2021-09-19 01:41
Hey @JoshuaRamey thanks for the interest!

The functional part of this feature is almost complete, it requires some extra work to be useful and then some polishing.
Apart from that, I think I will need to write a guide or something on how to configure AnkiConnect and connect from the app. For this, I would love to have your feedback. I'm planing on publishing a beta build through TestFlight in the next couple of days, that will include the bare bones of this functionality. If you are interested in testing it, I will post a download link + some instructions on how to install it.

I hope to have this working soon!

**Comment by JoshuaRamey** [comment] 2021-09-19 02:00
@juanj Sure, I would be happy to help test it.  Once you post the link and instructions I'll try it out and give you feedback / report any bugs I find.

**Comment by juanj** [comment] 2021-09-20 23:19
@JoshuaRamey Here is the link: https://testflight.apple.com/join/2hvkRQRO

And to configure and connect to AnkiConnect you should:
#### From your computer
1. Install [AnkiConnect](https://foosoft.net/projects/anki-connect/) as an add-on on Anki
2. Change the AnkiConnect configuration so the value of `webBindAddress` is `0.0.0.0` (the default value should be something similar to `127.0.0.1`)
3. Restart Anki

#### From the app
Make sure the device and your computer are in the same Wi-Fi network
1. After opening the app you should see a tab bar at the bottom. Select the second tab.
2. Tap the gear in the top-right corner
3. In the first text field you should enter the local ip of your computer followed by `:8765` unless you have changed the port number
4. If you defined a key in the AnkiConnect config, you should enter it in the second field, otherwise leave empty
5. Tap continue
6. Select deck, note type, sentence field, definition field, and image field (optional)

That should be all for the configuration.
To save a sentence, search for a word in the dictionary and tap the Anki icon.
When you want to sync your sentences, go to the sentences tab, and tap the arrow in the top-left corner.

As I said, this build includes only the bare bones, but is functional.

**Comment by JoshuaRamey** [comment] 2021-09-22 15:34
@juanj sorry for the late reply. I installed it and I made some cards when I had a chance to read. I haven't had a chance to sync those cards yet though. Maybe tomorrow? I'll give it a few tries and then write up some feedback and let you know if I find any bugs.

**Comment by JoshuaRamey** [comment] 2021-09-24 16:56
@juanj I managed to take some time to try it out. The functionality within the app seems fine but there is a problem when sending the cards to Anki. I followed your instructions and I'm able to select the deck and note type from what I have saved in Anki, but after syncing I cannot find those cards in my Anki deck. It seems that it's not adding them properly.

One suggestion: It would be nice if there were fields for [word] and [reading] (reading would be hiragana version or the word with furigana). Some people (myself included) like to put the word on the front of the card and the sentence on the back.

**Comment by juanj** [comment] 2021-09-26 21:07
@JoshuaRamey Hmm... That's interesting. I think it is most likely a connectivity issue. Can you update the app from Test Flight and try again? I added a better report for the syncing process.

Thanks for the suggestion! Definitely going to add those

**Comment by JoshuaRamey** [comment] 2021-09-29 16:34
@juanj 

It's working great after the update. Just a few pieces of feedback. In the sentences tab, if we didn't save a sentence then the entry shows up as blank in the list. Since every card is guaranteed to have a word maybe that would be better for the list.

As for the definitions, it would be great if we could include multiple on a single card. It helps with bilingual cards. But copy/paste also works fine.

![F607219E-4EE5-41A6-AA8B-482D30FCE374](https://user-images.githubusercontent.com/46817406/135310914-2c533ea1-0002-42d0-82f7-f3254b26a78c.jpeg)
![CB19E2C4-8AC4-4C8D-95D4-CB1D42D2BEBC](https://user-images.githubusercontent.com/46817406/135310926-6e86d2a6-3c69-4dc1-b8a4-a3ae36d8b71c.jpeg)

**Comment by JoshuaRamey** [comment] 2021-10-27 04:53
@juanj I found a bug. I synced a bunch of cards between the app and anki and when I check the cards in anki a lot of cards are using the image from the last card I created today rather than the images from the panels where I found those words.

**Comment by JoshuaRamey** [comment] 2021-12-04 15:36
@juanj hey I'm not sure if you saw the last comment. There is a bug when transferring the cards to Anki where the images get mixed up and many cards will use the same image. I'm not sure what the cause is, it's pretty random.

**Comment by juanj** [comment] 2021-12-04 18:33
Hey @JoshuaRamey sorry for the late response!

Nice catch! It appears to be an issue with the file name. The sentence is used to generate the file name of the image, so it becomes `<sentence>.png`. Because you are using empty sentences, the file name used for all the cards is the same, and Anki overwrites the existing images.
I will include a fix for this in the next TestFlight release. Thanks for finding it!

**Comment by JoshuaRamey** [comment] 2021-12-10 01:02
@juanj sorry for the late response.

Thanks, that should be easy to manage until you're able to fix it. I'll just throw the word in the sentence space.

**Comment by JoshuaRamey** [comment] 2022-02-03 13:41
@juanj I have been using the feature for a little while now and it works pretty well. The only problem I have discovered is that sometimes the image gets lost when transferring to Anki but I don't know what causes it. The message on the card says something about the file name.

But otherwise it works great.

**Comment by JoshuaRamey** [comment] 2022-03-14 07:50
@juanj Is there any chance you could renew the beta or add the anki support into the production version of the app? I'm currently unable to use the beta version of the app because it has expired. I have a road trip coming up this weekend and was hoping to read some manga during the ride.
![IMG_9394](https://user-images.githubusercontent.com/46817406/158127770-faf38f35-bcb2-48ca-a528-a942ae5e5883.jpg)

**Comment by JoshuaRamey** [comment] 2022-04-19 02:55
@juanj I have been using the feature for a while now and there are no major issues. I think you can merge this into your main branch if you want to. There is no reason to keep it in beta.

There is one very rare bug where an image sometimes gets lost, but it occurs so infrequently that I think it's ok for now.

I submitted an error report recently when trying to add a manga to my library. Please disregard it. I was an idiot and the manga I was trying to add was in an unsupported format.

**Comment by JoshuaRamey** [comment] 2022-04-19 03:14
I forgot to mention, allowing the user to add multiple definitions to a single flash card would be helpful. Personally I like to use both English and Japanese definitions on my cards. Currently I copy and paste, but it's a little tedious if the word has many definitions.

**Closed** 2022-04-24 21:31 UTC
Labels: High priority
